// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";

/**
 * What an open buffer was read against.
 *
 * `size` and `mtime_ns` are the cheap check; **`hash` is the decision**. Scope
 * §12: size and mtime alone never authorise overwriting.
 */
export type BaseRev = { size: bigint, mtime_ns: string, hash: ContentHash, };
