// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorSettings = { font_size: number, line_numbers: boolean, word_wrap: boolean, tab_size: number, };
