// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of an I/O failure, as a **typed code**.
 *
 * Scope §17 requires "disco cheio / permissão negada → erro visível", and the
 * frontend switches on the code and never reads a message (`ARCHITECTURE.md`
 * §7.3). A stringly-typed `kind` would have put the only distinguishing
 * information in the one field that is not the contract.
 */
export type IoKind = "disk_full" | "permission_denied" | "read_only_filesystem" | "not_found" | "is_a_directory" | "busy" | "name_too_long" | "interrupted" | "other";
