// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A path relative to the workspace root, `/`-separated, **exactly as the name
 * is on disk**.
 *
 * Never normalised and never rewritten: normalising Unicode here would produce
 * a string that does not open the file the user actually has, on any
 * filesystem that stores NFD (`ARCHITECTURE.md` §3). Comparison is
 * [`CompareKey`]'s job, not this type's.
 *
 * The parser is the **first** half of the root jail; the second half is
 * `notes-fs` re-resolving and re-checking at the moment of use, because a
 * symlink turns a valid-looking relative path into an escape.
 */
export type RelPath = string;
