// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseRev } from "./BaseRev";
import type { IoKind } from "./IoKind";

export type SaveResult = { "result": "saved", base_rev: BaseRev, buffer_version: bigint, unchanged: boolean, } | { "result": "conflict", disk_rev: BaseRev, buffer_version: bigint, } | { "result": "write_failed", kind: IoKind, buffer_version: bigint, };
