// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorSettings } from "./EditorSettings";
import type { FileSettings } from "./FileSettings";
import type { LinuxSettings } from "./LinuxSettings";
import type { MarkdownSettings } from "./MarkdownSettings";
import type { UiSettings } from "./UiSettings";

export type Settings = { schema: number, editor: EditorSettings, files: FileSettings, markdown: MarkdownSettings, ui: UiSettings, linux: LinuxSettings, };
