// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Caps } from "./Caps";
import type { WorkspaceId } from "./WorkspaceId";

export type WorkspaceInfo = { id: WorkspaceId, root: string, display_name: string, caps: Caps, case_insensitive: boolean, 
/**
 * True when this workspace's state was written by a newer build. Nothing
 * is overwritten in that case; the user is told rather than losing it.
 */
read_only: boolean, restored: boolean, };
