// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Assigned when a root is registered. Lives only in app data.
 */
export type WorkspaceId = string;
