// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A blake3 digest of a note's bytes.
 *
 * Serialised as `b3:<hex>` — **prefixed by the algorithm**, so that changing
 * hash one day is a migration and not an ambiguity. It is a *correlation*
 * signal, never identity (`ARCHITECTURE.md` §9).
 */
export type ContentHash = string;
