// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The seven states scope §9 requires the status bar to distinguish.
 *
 * Named in the model rather than assembled in the UI for one reason: **`Saved`
 * may only appear after the backend confirms**, which is a guarantee of the
 * core and not a convention for whoever writes the component. The frontend
 * computes the value from the last `SaveResult`, the open note's read-only
 * reason and the workspace's availability; it never invents a seventh.
 */
export type DocStatus = "saved" | "pending" | "writing" | "conflict" | "read_only" | "error" | "unavailable";
