// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";
import type { NativeId } from "./NativeId";

export type Stat = { size: bigint, 
/**
 * Nanoseconds since the Unix epoch. `i128` because a filesystem is free to
 * report a timestamp before 1970 or far past 2262, and neither should be a
 * panic in a note-taking app.
 */
mtime_ns: string, native_id: NativeId | null, kind: EntryKind, };
