// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Encoding } from "./Encoding";
import type { Eol } from "./Eol";

/**
 * What a file's bytes look like, detected on open and **re-applied on save**.
 *
 * This is the whole of front-matter preservation at 0.1a: nothing rewrites the
 * buffer, so YAML survives because no one touches it — not because a parser
 * puts it back (`ARCHITECTURE.md` §10).
 */
export type TextProfile = { encoding: Encoding, bom: boolean, eol: Eol, final_newline: boolean, };
