#!/usr/bin/env python3
"""Regenerate the committed fixture corpora: `basic/` and `edge-cases/`.

Both are committed, so this script exists to make them auditable and
reproducible rather than to run in CI. It is deterministic: running it on a
clean checkout must leave `git status` empty.

`xss/` is hand-written (each file is an assertion, not a sample) and
`large/` is generated by `gen-large.sh` and never committed.
"""
import hashlib
import pathlib
import shutil
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent / "fixtures"

WORDS = (
    "servidor firewall backup rede cliente projeto reunião nota tarefa deploy "
    "container volume índice consulta métrica alerta incidente runbook política "
    "chave rotação inventário topologia latência janela retenção"
).split()


def rng(seed: str, n: int) -> list[int]:
    """Deterministic byte stream from a seed — no `random`, no platform drift."""
    out, buf = [], b""
    while len(out) < n:
        buf = hashlib.blake2b(seed.encode() + buf, digest_size=64).digest()
        out.extend(buf)
    return out[:n]


def paragraph(seed: str, words: int) -> str:
    r = rng(seed, words)
    return " ".join(WORDS[b % len(WORDS)] for b in r)


def gen_basic() -> int:
    """~200 notes over a small tree, all plain LF with a final newline."""
    base = ROOT / "basic"
    if base.exists():
        shutil.rmtree(base)
    dirs = ["", "trabalho", "trabalho/projetos", "pessoal", "infra",
            "infra/servidores", "clientes", "arquivo/2025", "arquivo/2026"]
    for d in dirs:
        (base / d).mkdir(parents=True, exist_ok=True)

    n = 0
    for i in range(200):
        d = dirs[i % len(dirs)]
        name = f"nota-{i:03d}.md"
        seed = f"basic/{d}/{name}"
        body = [f"# {paragraph(seed + 'h', 4).title()}", ""]
        for p in range((i % 4) + 1):
            body.append(paragraph(f"{seed}/p{p}", 25 + (i + p) % 40))
            body.append("")
        if i % 7 == 0:
            body += ["## Lista", "", "- um", "- dois", "- três", ""]
        if i % 11 == 0:
            body += ["```bash", "echo hello", "```", ""]
        if i % 13 == 0:
            body += [f"Ver [outra nota](nota-{(i + 1) % 200:03d}.md).", ""]
        (base / d / name).write_bytes(("\n".join(body)).encode("utf-8"))
        n += 1

    # A handful of non-note files: the tree must list only .md/.markdown.
    (base / "README.txt").write_bytes(b"not a note\n")
    (base / "imagem.png").write_bytes(b"\x89PNG\r\n\x1a\n" + bytes(rng("png", 64)))
    (base / "infra" / "topologia.markdown").write_bytes(b"# Topologia\n\nok\n")
    (base / ".oculto.md").write_bytes(b"# hidden\n\nignored by default\n")
    # Ignored directories that git can actually store. A real `.git/` cannot be
    # committed as a fixture — git refuses to track a nested one — so the `.git`
    # entry of IGNORE_DEFAULT is covered by a unit test over a temp directory.
    for d in (".obsidian", ".notes", ".trash"):
        (base / d).mkdir(exist_ok=True)
        (base / d / "nota-que-nao-conta.md").write_bytes(b"# ignorada\n\nnao deve aparecer\n")
    return n


def gen_edge() -> list[str]:
    """One file per hazard the byte policy has to survive."""
    base = ROOT / "edge-cases"
    if base.exists():
        shutil.rmtree(base)
    base.mkdir(parents=True)
    BOM = b"\xef\xbb\xbf"
    files: dict[str, bytes] = {
        "lf.md":                 b"# lf\n\nlinha um\nlinha dois\n",
        "crlf.md":               b"# crlf\r\n\r\nlinha um\r\nlinha dois\r\n",
        "cr-only.md":            b"# cr\r\rlinha um\rlinha dois\r",
        "no-final-newline.md":   b"# sem newline final\n\nultima linha sem \\n",
        "bom-lf.md":             BOM + b"# bom + lf\n\ncorpo\n",
        "bom-crlf.md":           BOM + b"# bom + crlf\r\n\r\ncorpo\r\n",
        "mixed-eol.md":          b"# eol misto\n\nlinha lf\nlinha crlf\r\nlinha lf\n",
        "empty.md":              b"",
        "only-newline.md":       b"\n",
        "only-spaces.md":        b"   \n\t\n",
        "trailing-whitespace.md": b"# trailing\n\ntexto com espacos   \nfim\t\n",
        "invalid-utf8.md":       b"# invalido\n\n\xff\xfe nao e utf-8\n",
        "lone-surrogate-ish.md": b"# quase\n\n\xed\xa0\x80\n",
        "front-matter.md":       b"---\ntitle: Servidores\ntags:\n  - infra\n  - linux\ncreated: 2026-09-07\n---\n\n# Servidores\n\ncorpo\n",
        "front-matter-invalid.md": b"---\ntitle: [nao fecha\n  - :\n---\n\n# Ainda editavel\n\ncorpo\n",
        "front-matter-not-first.md": b"\n---\ntitle: nao conta\n---\n\n# corpo\n",
        "tabs.md":               b"# tabs\n\n\tindentado com tab\n\t\tmais fundo\n",
        "com espaco.md":         b"# nome com espaco\n\nok\n",
        "trailing-dot.md.":      b"# nome terminando em ponto\n\nilegal no Windows\n",
        "Duplicate.md":          b"# maiuscula\n\nA\n",
        "duplicate.md":          b"# minuscula\n\nb\n",
        "CASE.md":               b"# caixa alta\n\nok\n",
    }
    # Names differing only by Unicode normalisation: two files on Linux, one on
    # macOS. Written with explicit forms so the difference is in the bytes.
    files[unicodedata.normalize("NFC", "café-nfc.md")] = b"# nfc\n\nok\n"
    files[unicodedata.normalize("NFD", "café-nfd.md")] = b"# nfd\n\nok\n"
    files["acentuacao-ção.md"] = b"# acentuacao no nome\n\nok\n"

    written = []
    for name, data in files.items():
        try:
            (base / name).write_bytes(data)
            written.append(name)
        except OSError as e:            # e.g. trailing dot on Windows
            print(f"  skipped {name!r}: {e}", file=sys.stderr)

    # 5 MB, deterministic, and not compressible into nothing.
    big = base / "large-5mb.md"
    with big.open("wb") as f:
        f.write(b"# 5 MB\n\n")
        written_bytes = 9
        i = 0
        while written_bytes < 5 * 1024 * 1024:
            line = (paragraph(f"big/{i}", 18) + "\n").encode("utf-8")
            f.write(line)
            written_bytes += len(line)
            i += 1
    written.append("large-5mb.md")
    return written


if __name__ == "__main__":
    n = gen_basic()
    e = gen_edge()
    print(f"basic: {n} notes")
    print(f"edge-cases: {len(e)} files")
